In [5]:
import os
import pandas as pd

folder_path = r"raw data\dynamic_events_pl_24"

# List all parquet files
files = [f for f in os.listdir(folder_path) if f.lower().endswith(".parquet")]
print("Parquet files found:", files)

for filename in files:
    file_path = os.path.join(folder_path, filename)
    df_name = os.path.splitext(filename)[0]  # remove .parquet extension
    try:
        globals()[df_name] = pd.read_parquet(file_path)
        print(f"DataFrame '{df_name}' created with shape {globals()[df_name].shape}")
    except Exception as e:
        print(f"Error reading {filename}: {e}")

Parquet files found: ['matches.parquet', 'players.parquet', 'teams.parquet']
DataFrame 'matches' created with shape (380, 8)
DataFrame 'players' created with shape (686, 7)
DataFrame 'teams' created with shape (20, 4)

In [9]:
# Expand 'home_team' and 'away_team' dictionaries
home_df = pd.json_normalize(matches['home_team']).add_prefix('home_')
away_df = pd.json_normalize(matches['away_team']).add_prefix('away_')

# Drop the original dict columns and concatenate the new ones
matches_expanded = pd.concat([matches.drop(['home_team', 'away_team'], axis=1), home_df, away_df], axis=1)

matches_expanded.head()

,id,date_time,status,competition_id,season_id,competition_edition_id,home_id,home_short_name,away_id,away_short_name
0,2018571,2025-05-25T15:00:00Z,closed,1,95,895,63,Bournemouth,62,Leicester
1,2018572,2025-05-25T15:00:00Z,closed,1,95,895,48,Fulham,40,Manchester City
2,2018573,2025-05-25T15:00:00Z,closed,1,95,895,752,Ipswich Town,37,West Ham
3,2018574,2025-05-25T15:00:00Z,closed,1,95,895,2,Liverpool,60,Crystal Palace
4,2018575,2025-05-25T15:00:00Z,closed,1,95,895,31,Manchester U,39,Aston Villa

In [7]:
players.head()

,id,first_name,last_name,short_name,birthday,trackable_object,gender
0,18589,Max,Aarons,M. Aarons,2000-01-04,18786,male
1,967750,Zach,Abbott,Z. Abbott,2006-05-13,969313,male
2,514681,Joshua Kofi,Acheampong,J. Acheampong,2006-05-05,516238,male
3,24629,Tyler,Adams,T. Adams,1999-02-14,25664,male
4,11589,Oluwatosin,Adarabioyo,T. Adarabioyo,1997-09-24,11670,male

In [10]:
# Expand the 'stadium' dictionary
stadium_df = pd.json_normalize(teams['stadium']).add_prefix('stadium_')

# Drop the original 'stadium' column and concatenate the new ones
teams_expanded = pd.concat([teams.drop('stadium', axis=1), stadium_df], axis=1)

teams_expanded.head()

,id,name,coach,stadium_capacity,stadium_city,stadium_id,stadium_name
0,39,Aston Villa,None,42682.0,Birmingham,488,Villa Park
1,754,Brentford FC,None,NaN,London,1970,Brentford Community Stadium
2,37,West Ham United,None,60000.0,London,52,Stade Olympique de Londres
3,31,Manchester United,None,75635.0,Manchester,63,Old Trafford
4,41,Everton,None,39571.0,Liverpool,89,Goodison Park